mozilla/fxa-shared

index.js, l10n/localizeTimestamp.js, package.json, test/l10n/localizeTimestamp.js, test/l10n/supportedLanguages.js
=> feat(l10n): add localize timestamp utility

LICENSE
=> chore(license): Add MPL2 LICENSE file

l10n/supportedLanguages.json
=> fix(l10n): Add support for fy-NL

l10n/supportedLanguages.json
Fixes https://github.com/mozilla/fxa/issues/268
=> Add cak locale

.travis.yml, package.json
Ref: https://nodesecurity.io/advisories/532
=> chode(deps): update deps

package.json, test/index.js, test/l10n/localizeTimestamp.js, test/l10n/supportedLanguages.js
Fixes #15.
@mozilla/fxa-devs r?
=> chore(tests): migrate from tap to mocha+chai

.eslintrc, .travis.yml, l10n/localizeTimestamp.js, package.json
Fixes https://github.com/mozilla/fxa-shared/issues/16
=> fix(lint-setup): #16 added lint setup

index.js, metrics/amplitude.js, test/index.js, test/metrics/amplitude.js
Fixes #11.
WIP until the auth server tests are fixed and some tests are written for this repo.
Related PRs for content and auth servers:
* https://github.com/mozilla/fxa-content-server/pull/6022
* https://github.com/mozilla/fxa-auth-server/pull/2384
@irrationalagent, this is the PR I mentioned just now.
=> feat(metrics): extract common code for emitting amplitude events

metrics/amplitude.js, test/metrics/amplitude.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2409
@mozilla/fxa-devs r?
=> fix(emails): add `lowRecoveryCodesEmail` email template

l10n/supportedLanguages.json
fixes #25
@mozilla/fxa-devs - r?
=> feat(l10n): Enable nb-NO locale.

package.json
=> chore(package): bump to 1.0.10

package.json
=> chore(release): Bump to 1.0.12

package.json
This release includes the new oauth scope-cehcking stuff.
=> Merge v1.0.13 to master.

package.json
Noticed this never merged to `master` and wanted to get it in before I PR other changes.
@mozilla/fxa-devs r?
=> Merge v1.0.15 tag into master

l10n/supportedLanguages.json
fixes #49
fixes mozilla/fxa-content-server-l10n#322
@mozilla/fxa-devs - r?
=> feat(l10n): Enable Catalan (ca)

.travis.yml
=> feat(test): Test on node 8 and 10 rather than 6 and 8

metrics/amplitude.js, test/metrics/amplitude.js
I missed this yesterday in #52.
blocks mozilla/fxa-content-server#6895
@mozilla/fxa-devs - r?
=> fix(metrics): Add an entry to EVENT_PROPERTIES for `notify` group.

package.json
=> Merge 1.0.19 into master

package-lock.json, package.json
=> Merge 1.0.20 into master

package-lock.json, package.json
=> Merge 1.0.21 into master

redis/connection.js, test/redis/connection.js, test/redis/integration.js
Blocks mozilla/fxa-auth-server#2990.
We need to pop verification reminders atomically, which we can do with Redis `MULTI` and `EXEC`. This change just wraps those round `zrangebyscore` and `zremrangebyscore`, similar to what we did previously for the `update` command. It also removes `zremrangebyscore` from the interface because we have no need to call it and don't want non-atomic usage creeping in in the future.
@mozilla/fxa-devs r?
=> feat(redis): implement atomic zpoprangebyscore method for sorted sets

package-lock.json, package.json
=> Merge 1.0.22 into master

package-lock.json, package.json
=> Merge 1.0.23 into master
